/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Frederik
 */
public class TschenrechnerGUI extends javax.swing.JFrame {

    /**
     * Creates new form TschenrechnerGUI
     */
    public TschenrechnerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        dividButton = new javax.swing.JButton();
        aplusb = new javax.swing.JLabel();
        aminusb = new javax.swing.JLabel();
        atimesb = new javax.swing.JLabel();
        adividedb = new javax.swing.JLabel();
        SolutionLabel = new javax.swing.JLabel();
        aIN = new javax.swing.JFormattedTextField();
        bIN = new javax.swing.JFormattedTextField();
        SolutionOut = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        aLabel.setText("a");

        bLabel.setText("b");

        plusButton.setText("go");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setText("go");
        minusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minusButtonMouseClicked(evt);
            }
        });

        multiplicationButton.setText("go");
        multiplicationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                multiplicationButtonMousePressed(evt);
            }
        });

        dividButton.setText("go");
        dividButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dividButtonMouseReleased(evt);
            }
        });
        dividButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividButtonActionPerformed(evt);
            }
        });

        aplusb.setText("a+b");

        aminusb.setText("a-b");

        atimesb.setText("a*b");

        adividedb.setText("a/b");

        SolutionLabel.setText("Solution");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SolutionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SolutionOut, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aIN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bIN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(minusButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aminusb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dividButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(plusButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aplusb)
                                .addGap(36, 36, 36)
                                .addComponent(multiplicationButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adividedb)
                            .addComponent(atimesb))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aLabel)
                    .addComponent(plusButton)
                    .addComponent(aplusb)
                    .addComponent(aIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicationButton)
                    .addComponent(atimesb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLabel)
                    .addComponent(minusButton)
                    .addComponent(aminusb)
                    .addComponent(bIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dividButton)
                    .addComponent(adividedb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SolutionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SolutionOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dividButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dividButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
double a = (double)((Double.parseDouble(aIN.getText())));
double b = (double)((Double.parseDouble(bIN.getText())));
double c;
c=a+b;
    SolutionOut.setValue(c);
    // TODO add your handling code here:
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minusButtonMouseClicked
double a = (double)((Double.parseDouble(aIN.getText())));
double b = (double)((Double.parseDouble(bIN.getText())));
double c;
c=a-b;
    SolutionOut.setValue(c);
    // TODO add your handling code here:
    }//GEN-LAST:event_minusButtonMouseClicked

    private void multiplicationButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicationButtonMousePressed
double a = (double)((Double.parseDouble(aIN.getText())));
double b = (double)((Double.parseDouble(bIN.getText())));
double c;
c=a*b;
    SolutionOut.setValue(c);   // TODO add your handling code here:
    }//GEN-LAST:event_multiplicationButtonMousePressed

    private void dividButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividButtonMouseReleased
     double a = (double)((Double.parseDouble(aIN.getText())));
double b = (double)((Double.parseDouble(bIN.getText())));
double c;
c=a/b;
    SolutionOut.setValue(c);   // TODO add your handling code here:
    }//GEN-LAST:event_dividButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TschenrechnerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TschenrechnerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TschenrechnerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TschenrechnerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TschenrechnerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SolutionLabel;
    private javax.swing.JFormattedTextField SolutionOut;
    private javax.swing.JFormattedTextField aIN;
    private javax.swing.JLabel aLabel;
    private javax.swing.JLabel adividedb;
    private javax.swing.JLabel aminusb;
    private javax.swing.JLabel aplusb;
    private javax.swing.JLabel atimesb;
    private javax.swing.JFormattedTextField bIN;
    private javax.swing.JLabel bLabel;
    private javax.swing.JButton dividButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton plusButton;
    // End of variables declaration//GEN-END:variables
}
